FROM golang:bookworm

WORKDIR /

RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

RUN xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive

RUN curl https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg

RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ bullseye main"
RUN tee /etc/apt/sources.list.d/cloudflare-client.list
RUN apt update -y \
    && apt install -y cloudflare-warp \
    && echo y | warp-cli registration new \
    && warp-cli mode proxy

EXPOSE 80
EXPOSE 443

COPY ./cmd.sh /cmd.sh

ENTRYPOINT ["/cmd.sh"]